---
name: CI
on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:
    branches: ['**']
  workflow_dispatch: # NOTE: add manual triggers and parameters here

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Configure env
        run: |
          \builtin . ./tool/local/ci_config.bash

      - name: Install dependencies
        run: |
          [[ ! -e .env.sh ]] || \builtin . ./.env.sh
          \builtin . ubuntu_ci_install.bash

      - name: Run Redo for all build/check/test targets
        run: |
          [[ ! -e .env.sh ]] || \builtin . ./.env.sh
          \builtin . ci_run.bash
